[pytest]
markers=
    login_link: marker for login link in header
    user_add_product_to_basket: mark for tests - user can add a product to the basket from a product page
    need_review: mark for review